name: secp256k1-schnorr
version: 0.0.1
synopsis: Schnorr signatures for secp256k1
description: Schnorr signatures using the secp256k1 library.
category: Crypto
author: Sascha-Oliver Prolic
maintainer: saschaprolic@googlemail.com
copyright: (c) 2022 Sascha-Oliver Prolic
license: MIT
license-file: LICENSE
github: prolic/secp256k1-schnorr.git
homepage: https://github.com/prolic/secp256k1-schnorr#readme
verbatim:
  cabal-version: 1.24
extra-source-files:
  - CHANGELOG.md
  - README.md
dependencies:
  - base >=4.9 && <5
  - base16 >=0.3.0.1
  - bytestring >=0.10.8 && <0.11
  - cereal >=0.5.4 && <0.6
  - cryptohash-sha256 >= 0.11.102.1 && <0.12
  - entropy >=0.3.8 && <0.5
  - deepseq >=1.4.2 && <1.5
  - DRBG >=0.5.5 && <0.6
  - hashable >=1.2.6 && <1.4
  - QuickCheck >=2.9.2 && <2.15
  - string-conversions >=0.4 && <0.5
  - text
  - unliftio-core >=0.1.0 && <0.3
  - utf8-string >= 1.0.2 && <1.1
library:
  source-dirs: src
  pkg-config-dependencies:
    - libsecp256k1
  extra-lib-dirs:
    - /usr/local/lib
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    pkg-config-dependencies:
      - libsecp256k1
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
      - -static
    ld-options: -static -pthread
    cc-options: -static
    verbatim:
      build-tool-depends:
          hspec-discover:hspec-discover
    dependencies:
      - hspec
      - secp256k1-schnorr
      - mtl
      - HUnit
