name: secp256k1-schnorr
version: 0.0.1
synopsis: Schnorr signatures for secp256k1
description: Schnorr signatures using the secp256k1 library.
category: Crypto
author: Sascha-Oliver Prolic
maintainer: saschaprolic@googlemail.com
copyright: (c) 2022 Sascha-Oliver Prolic
license: MIT
license-file: LICENSE
github: prolic/secp256k1-schnorr.git
homepage: http://github.com/prolic/secp256k1-schnorr#readme
verbatim:
  cabal-version: 1.24
extra-source-files:
  - CHANGELOG.md
  - README.md
dependencies:
  - base >=4.9 && <5
  - base16 >=0.3.0.1
  - bytestring >=0.10.8 && <0.11
  - cereal >=0.5.4 && <0.6
  - entropy >=0.3.8 && <0.5
  - deepseq >=1.4.2 && <1.5
  - hashable >=1.2.6 && <1.4
  - QuickCheck >=2.9.2 && <2.15
  - string-conversions >=0.4 && <0.5
  - unliftio-core >=0.1.0 && <0.3
library:
  source-dirs: src
  pkg-config-dependencies:
    - libsecp256k1
  when:
  - condition: flag(schnorr)
    cpp-options: -DSCHNORR
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    verbatim:
      build-tool-depends:
          hspec-discover:hspec-discover
    dependencies:
      - hspec
      - secp256k1-schnorr
      - mtl
      - HUnit

flags:
  schnorr:
    description: "Enable BIP-340 (Schnorr) APIs"
    manual: true
    default: false
